services:
  olivos-app:
    image: shiaworkshop/olivos:latest
    container_name: olivos-main
    stdin_open: true
    tty: true
    working_dir: /app
    volumes:
      - "./OlivOS:/app"
      - "./napcat/config:/app/napcat/config"
    environment:
      - LOGIN_UIN=${ACCOUNT}
    networks:
      - olivos_network
    depends_on:
      - napcat

  napcat:
    image: mlikiowa/napcat-docker:latest
    container_name: napcat
    ports:
      - "6099:6099"
    volumes:
      - "./napcat/config:/app/napcat/config"
      - "./napcat/QQ_DATA:/app/.config/QQ"
      - "./OlivOS/plugin:/app/plugin"
    environment:
      - NAPCAT_UID=${NAPCAT_UID:-1000}
      - NAPCAT_GID=${NAPCAT_GID:-1000}
      - ACCOUNT=${ACCOUNT}
    networks:
      - olivos_network

networks:
  olivos:
    driver: bridge
