services:
  olivos-app:
    image: shiaworkshop/olivos:latest
    container_name: olivos-container
    stdin_open: true
    tty: true
    working_dir: /app
    volumes:
      - "${OLIVOS_DATA}/OlivOS:/app"
    environment:
      - LOGIN_UIN=${LOGIN_UIN}
    networks:
      - olivos
    depends_on:
      - go-cqhttp

  go-cqhttp:
    image: shiaworkshop/olivos-go-cqhttp:latest
    container_name: go-cqhttp
    volumes:
      - "${OLIVOS_DATA}/go-cqhttp:/app/go-cqhttp-data"
    working_dir: /app
    environment:
      - LOGIN_UIN=${LOGIN_UIN}
      - LOGIN_PASSWD=${LOGIN_PASSWD}
    networks:
      - olivos

networks:
  olivos:
    driver: bridge
