name: Docker Build and Push

on:
  workflow_dispatch:  # 添加手动触发支持
  repository_dispatch: []  # 移除旧触发方式

env:
  DOCKERHUB_REPO: shiaworkshop/olivos
  DOCKERFILE_PATH: OlivOS/Dockerfile

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: 读取上游版本号
        id: read_version
        run: |
          UPSTREAM_TAG=$(cat last_release.txt)
          echo "UPSTREAM_TAG=$UPSTREAM_TAG" >> $GITHUB_ENV

      - name: 获取上游 Commit SHA
        id: get_commit_sha
        run: |
          RESPONSE=$(curl -s \
            -H "Authorization: Bearer ${{ secrets.GH_PAT }}" \
            -H "Accept: application/vnd.github.v3+json" \
            "https://api.github.com/repos/OlivOS-Team/OlivOS/git/ref/tags/${{ env.UPSTREAM_TAG }}")
          
          COMMIT_SHA=$(echo "$RESPONSE" | jq -r .object.sha)
          echo "COMMIT_SHA=$COMMIT_SHA" >> $GITHUB_ENV

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: 构建并推送镜像
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ${{ env.DOCKERFILE_PATH }}
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ${{ env.DOCKERHUB_REPO }}:${{ env.UPSTREAM_TAG }}
            ${{ env.DOCKERHUB_REPO }}:${{ env.COMMIT_SHA }}
            ${{ env.DOCKERHUB_REPO }}:latest
