name: Sync OlivOS Release

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */6 * * *'

jobs:
  check-and-create-release:
    runs-on: ubuntu-latest
    outputs:
      new_release_created: ${{ steps.create_release.outputs.new_release || 'false' }}
      release_tag: ${{ steps.create_release.outputs.release_tag || '' }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: 读取当前跟踪的上游版本
        id: read_last_version
        run: |
          if [ -f "last_release.txt" ]; then
            echo "LAST_VERSION=$(cat last_release.txt)" >> $GITHUB_ENV
          else
            echo "LAST_VERSION=0.0.0" >> $GITHUB_ENV
          fi

      - name: 获取上游最新 Release
        id: get_upstream_release
        uses: dawidd6/action-get-latest-release@v7.0.0
        with:
          repository: 'OlivOS-Team/OlivOS'
          token: ${{ secrets.GH_PAT }}

      - name: 检查是否需要处理
        id: check_version
        run: |
          if [[ "${{ env.LAST_VERSION }}" < "${{ steps.get_upstream_release.outputs.tag }}" ]]; then
            echo "NEW_RELEASE=true" >> $GITHUB_ENV
          else
            echo "NEW_RELEASE=false" >> $GITHUB_ENV
          fi

      - name: 处理新版本
        id: create_release
        if: env.NEW_RELEASE == 'true'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # 转换标签名
          CLEAN_TAG=$(echo "${{ steps.get_upstream_release.outputs.tag }}" | sed -E 's/[^a-zA-Z0-9.-]+/-/g; s/^-//; s/-+/-/g; s/-$//')

          # 创建 Release
          curl -X POST \
            -H "Authorization: Bearer $GITHUB_TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            "https://api.github.com/repos/${{ github.repository }}/releases" \
            -d '{
              "tag_name": "'"${CLEAN_TAG}"'",
              "name": "",
              "body": "由官方项目发布 release 自动触发",
              "draft": false,
              "prerelease": false
            }'

          # 传递输出变量
          echo "new_release=true" >> $GITHUB_OUTPUT
          echo "release_tag=${CLEAN_TAG}" >> $GITHUB_OUTPUT
